name: Push Image
on:
  pull_request_target:
    branches:
      - main
    
jobs:
  push-docker-image:
    name: Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Build Image
        run: docker/build.sh
