name: new-issue-announce-action
on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Issue Details
        run: |
          export issue_title=$(echo "${{ github.event.issue.title }}" | sed -e "s/'//g" -e 's/"//g')
          echo "Issue creator: ${{ github.event.issue.user.login }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue url: ${{ github.event.issue.html_url }}"
          echo "Using issue_title: $issue_title"
      - name: Curl My Personal Site
        run: |
            export issue_title=$(echo "${{ github.event.issue.title }}" | sed -e "s/'//g" -e 's/"//g')
            curl --location --request GET 'thi3nl0ng.github.io' \
            --header 'Content-Type: application/json; charset=UTF-8' \
            --data "{'text': '[${{ github.event.issue.number }}] ${{ github.event.issue.html_url }} $issue_title (${{ github.event.issue.user.login }})'}"
