 on: [pull_request_target]

 jobs:
   add_pr_comment:
     permissions: write-all
     runs-on: ubuntu-latest
     name: OpenAI PR Comment
     env:
       GIT_COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       PR_NUMBER: ${{ github.event.pull_request.number }}
       PR_TITLE: ${{ github.event.pull_request.title }}      

     steps:
       - uses: actions/checkout@v3
         with:
           ref: ${{ github.event.pull_request.head.sha }}  

       - run: |
           echo "PR Branch is: ${{ github.event.pull_request.head.ref }}"
